name: sajiloschool
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  shared_preferences: ^0.5.5 #0.5.6+1
  nepali_date_picker: ^3.2.0+1
  http: ^0.12.0+4
  shimmer: ^1.1.1
  bottom_navy_bar: ^5.4.0
  autocomplete_textfield: ^1.7.3
  simple_animations: ^1.3.11
  rxdart: ^0.23.1
  flutter_downloader: ^1.4.4
  permission_handler: ^5.0.0+hotfix.5
  path_provider: ^1.6.7
  dio: ^3.0.9
  open_file: ^3.0.1 #file open
  fluttertoast: ^4.0.1
  url_launcher: ^5.4.5
  flutter_offline: ^0.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/logo/drawerlogo.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
